apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.orgName | dump }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: sahana-sivaraj-99x/e-commerce-docs
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: sahana-sivaraj-99x_e-commerce-docs
    snyk.io/org-id: c6467e61-5fc2-4f7a-b56b-0f4912257c1f
    snyk.io/target-id: c06a52f0-3288-490f-88b3-cb6d2f12c2f3
    snyk.io/project-ids: 69e5a9a3-462d-401e-94b5-246e1bf7ff17,379ceb8b-1fc9-417a-8b76-e46a4ac1ef9c,88e41f87-5f2d-4b65-8262-ae6e4ce04167,ae231d1a-a2bd-4174-8411-a9056db9f549
    grafana/overview-dashboard: https://sahanasivaraj99x.grafana.net/public-dashboards/bcd8505dd3d749dcb7eb40c8f92b0011?orgId=11

spec:
  type: website
  owner: ${{ values.owner | dump }}
  lifecycle: experimental